### ISSUE TITLE
Typo in example code

### ISSUE THREAD

**Issue by cym13** [atilaneves/cerealed#12]
I didn't want to go through the trouble of making a full pull request for so little but on the other hand it's important that example code work without any problem:

    diff --git a/README.md b/README.md
    index 192b10f..a700ea0 100644
    --- a/README.md
    +++ b/README.md
    @@ -15,7 +15,7 @@ Example usage:
         cerealiser ~= cast(ubyte)42;
         assert(cerealiser.bytes == [ 0, 0, 0, 5, 42]);
     
    -    auto deceralizer = Decerealizer([ 0, 0, 0, 5, 42]); //US spelling works too
    +    auto decerealizer = Decerealizer([ 0, 0, 0, 5, 42]); //US spelling works too
         assert(decerealizer.value!int == 5);
         assert(decerealizer.value!ubyte == 42);

**Comment by atilaneves** [comment]
Thanks!
